name: Deploy to GitHub Pages and Aliyun OSS

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.18.0'

      - name: Install dependencies using pnpm
        run: |
          npm install -g pnpm
          pnpm install

      - name: Build the project
        run: pnpm run build

      - name: Deploy to GitHub Pages
        run: |
          pnpm install -g gh-pages
          gh-pages -d dist

      - name: Upload to Aliyun OSS
        env:
          OSS_REGION: ${{ secrets.OSS_REGION }}
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          OSS_BUCKET: ${{ secrets.OSS_BUCKET }}
        run: |
          curl -L https://github.com/aliyun/ossutil/releases/latest/download/ossutil64 -o ossutil
          chmod 755 ossutil
          ./ossutil config --endpoint=$OSS_REGION --access-key-id=$OSS_ACCESS_KEY_ID --access-key-secret=$OSS_ACCESS_KEY_SECRET
          ./ossutil cp -r dist/ oss://$OSS_BUCKET/ --update

      - name: Refresh Aliyun DCDN Cache
        env:
          DCDN_ACCESS_KEY_ID: ${{ secrets.DCDN_ACCESS_KEY_ID }}
          DCDN_ACCESS_KEY_SECRET: ${{ secrets.DCDN_ACCESS_KEY_SECRET }}
        run: |
          # Install aliyun-cli
          curl -L https://github.com/aliyun/aliyun-cli/releases/latest/download/aliyun-cli-linux-amd64 -o aliyun
          chmod +x aliyun
          sudo mv aliyun /usr/local/bin/
          
          # Configure aliyun-cli with your credentials
          aliyun configure set --access-key-id $DCDN_ACCESS_KEY_ID --access-key-secret $DCDN_ACCESS_KEY_SECRET --region cn-hangzhou
          
          # Refresh DCDN cache (adjust ObjectPath to your needs)
          aliyun dcdn RefreshObjectCaches --ObjectPath "https://docs.workstatic.cn/*" --ObjectType "Directory"
